#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyCoMobile.Resource", IsApplication=true)]

namespace MyCoMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int animate_lady = 2131034112;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int appthemewhite_background = 2131230720;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ani0_logo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ani1_logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ani2_myco = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ani3_creations = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ani4_creating = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ani5_injoy = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ani6_imagine = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ani7_innerstand = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int blog = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int boutique = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int circle_bg3 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int games = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int gradient = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_launcher = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int rrus = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int shopmyco = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int turnplate_bg_left = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int turnplate_bg_right = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int turnplate_center_unlogin = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int turnplate_mask_unlogin_normal = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int videos = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int wheel = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0005
			public const int circle_menu_item_center = 2131427333;
			
			// aapt resource value: 0x7f0b0000
			public const int circle_menu_item_image = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int circle_menu_item_text = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int launchCenterview = 2131427330;
			
			// aapt resource value: 0x7f0b0006
			public const int mainWebView = 2131427334;
			
			// aapt resource value: 0x7f0b0009
			public const int menuShopBoutique = 2131427337;
			
			// aapt resource value: 0x7f0b0008
			public const int menuShopHerbs = 2131427336;
			
			// aapt resource value: 0x7f0b0007
			public const int menuShopMyCo = 2131427335;
			
			// aapt resource value: 0x7f0b0004
			public const int menulayout = 2131427332;
			
			// aapt resource value: 0x7f0b0003
			public const int vwIntroVideo = 2131427331;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int circle_menu_item = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Launcher = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main2 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Web = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int menu = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ani0_logo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ani1_logo = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ani2_myco = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ani3_creations = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ani4_creating = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ani5_injoy = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ani6_imagine = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ani7_innerstand = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ic_launcher = 2130903048;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int opener_vid = 2131099648;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int btn4 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int btn5 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int btn6 = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int btnShopBoutique = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int btnShopHerbs = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int btnShopMyco = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int hello_world = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int imglauncher = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int launcher_label = 2131165186;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int AppTheme = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int AppThemeWhite = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int Splash = 2131296258;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
